name: PR opened / edited

on:
  pull_request:
    types: [opened, edited]

# env:
  # GITHUB_BRANCH: ${{ github.ref }}
  # GITHUB_SOURCE: ${{ github.pull_request.head.ref }}
  # GITHUB_TARGET: ${{ github.pull_request.base.ref }}
  # PR_TO_DEVELOP: ${ GITHUB_TARGET } == 'refs/heads/develop'
  # PR_TO_DEVELOP: ${{ env.GITHUB_TARGET }} == 'refs/heads/develop'

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - name: hi
        run: echo 'hi'

  hi-main:
    # if: ${{ github.pull_request.head.ref }} == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=source;]$(echo ${GITHUB_HEAD_REF##*/})"
          echo "##[set-output name=target;]$(echo ${GITHUB_BASE_REF##*/})"
        id: extract_branch
      
      - name: hi main
        run: |
          echo 'hi main'
          echo 'hi again'
